services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file: ./mysql/.env
    networks:
      homeserver-network:

  nextcloud:
    image: nextcloud
    restart: always
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    env_file: ./nextcloud/.env
    networks:
      homeserver-network:

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      homeserver-network:

  stirling_pdf:
    image: frooodle/s-pdf:latest
    volumes:
      - trainingData:/usr/share/tessdata 
      - extraConfigs:/configs
#      - ./customFiles:/customFiles/
#      - ./logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    networks:
      homeserver-network:

  blog:
    image: ghost:5-alphine
    restart: always
    env_file: ./ghost/.env
    volumes:
      - ghost:/var/lib/ghost/content:rw
    networks:
      homeserver-network:

networks:
  homeserver-network:
    ipam:
      config:
        - subnet: 10.10.10.0/24
volumes:
  nextcloud:
  db:
  ghost:
  trainingData:
  extraConfigs:

